name: mixpanel_analytics
description:
  A dart wrapper on the mixpanel REST API to be used in Flutter applications.
  As this is using the http REST API it works both with Android and iOS.
version: 2.1.1
homepage: https://github.com/Alpha-health/mixpanel_analytics
repository: https://github.com/Alpha-health/mixpanel_analytics
issue_tracker: https://github.com/Alpha-health/mixpanel_analytics/issues

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: any
  mockito: any
